name: .NET Build & Test

on:
  push:
    branches: [ main ]  # or "master" depending on your branch
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # or 6.0.x or whichever you’re using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore

    - name: Run tests (if you have any)
      run: dotnet test --no-build --verbosity normal
